version: '3.9'

services:

  bot:
    build: ./bot
    container_name: auto_bot
    env_file:
      - .env
    volumes:
      - ./rag_services.csv:/app/rag_services.csv
    depends_on:
      - ollama
      - chromadb
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "12000:11434"
    restart: unless-stopped

  chromadb:
    build: ./db
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

volumes:
  ollama_data:
  chroma_data:
